FROM    makuk66/docker-solr
MAINTAINER  Craig Trim "craigtrim@gmail.com"

#RUN mkdir -p /opt/solr/server/solr/books
#RUN mkdir -p /opt/solr/server/solr/books/data
#RUN mkdir -p /opt/solr/server/solr/books/conf/lang

#ADD core.properties /opt/solr/server/solr/books/
#ADD solrconfig.xml /opt/solr/server/solr/books/conf/
#ADD schema.xml /opt/solr/server/solr/books/conf/
#ADD stopwords.txt /opt/solr/server/solr/books/conf/
#ADD stopwords_en.txt /opt/solr/server/solr/books/conf/lang/
#ADD synonyms.txt /opt/solr/server/solr/books/conf/
#ADD protwords.txt /opt/solr/server/solr/books/conf/
#ADD elevate.xml /opt/solr/server/solr/books/data/